#!/usr/bin/env node
// Regenerates packages/core/src/data/xsd/index.ts from the official CBI XSDs
// kept under packages/core/xsd-source/. Run with: pnpm --filter @sepalo/core embed:xsd

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CORE_ROOT = join(__dirname, '..');
const SCHEMA_DIR = join(CORE_ROOT, 'xsd-source', 'CBIPaymentRequestMsg.00.04.01');
const OUT_FILE = join(CORE_ROOT, 'src', 'data', 'xsd', 'index.ts');

const CBI_PAYMENT_REQUEST = await readFile(
  join(SCHEMA_DIR, 'CBIPaymentRequest.00.04.01.xsd'),
  'utf8',
);
const CBI_BODY = await readFile(join(SCHEMA_DIR, 'CBIBdyPaymentRequest.00.04.01.xsd'), 'utf8');

// Minimal stub for the CBISgnInf XSD imported by the Body schema.
// We never emit <CBISgnInf> (digital signature), so we only need a type
// declaration that satisfies the xs:import statement.
const CBI_SGN_INF_STUB = `<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:CBI:xsd:CBISgnInf.001.04"
  xmlns="urn:CBI:xsd:CBISgnInf.001.04"
  elementFormDefault="qualified">
  <xs:complexType name="CBISgnInf.001.04">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
`;

function assertSafe(name, content) {
  if (content.includes('`') || content.includes('${')) {
    throw new Error(`${name} contains a template-literal special char; cannot embed safely.`);
  }
}

function escapeForTemplateLiteral(content) {
  // Escape backslashes so XSD regex patterns like `\+[0-9]+` survive embedding.
  return content.replace(/\\/g, '\\\\');
}

assertSafe('CBIPaymentRequest', CBI_PAYMENT_REQUEST);
assertSafe('CBIBdyPaymentRequest', CBI_BODY);
assertSafe('CBISgnInf stub', CBI_SGN_INF_STUB);

const out = `// Generated by scripts/embed-xsd.mjs — do not edit by hand.
// Source: XML Schema v.00.04.01 (CBI, entrata in vigore 17/03/2024)
// To refresh: pnpm --filter @sepalo/core embed:xsd

export const CBI_PAYMENT_REQUEST_XSD = \`${escapeForTemplateLiteral(CBI_PAYMENT_REQUEST)}\`;

export const CBI_BODY_XSD = \`${escapeForTemplateLiteral(CBI_BODY)}\`;

export const CBI_SGN_INF_XSD = \`${escapeForTemplateLiteral(CBI_SGN_INF_STUB)}\`;

// Legacy alias retained for compatibility with earlier handwritten schema.
export const CBI_PAYMENT_XSD = CBI_BODY_XSD;
`;

await writeFile(OUT_FILE, out, 'utf8');
console.log(`Wrote ${OUT_FILE}`);
